build: off

environment:
  matrix:
    - job_name: Ubuntu
      appveyor_build_worker_image: Ubuntu2004
      APPVEYOR: True
      CI: True
    - job_name: MacOS
      appveyor_build_worker_image: macos
      APPVEYOR: True
      CI: True
    # - job_name: Windows
    #   appveyor_build_worker_image: Visual Studio 2019
    #   CHERE_INVOKING: 1
    #   MSYSTEM: MINGW64
    #   RUBY_VERSION: 27

for:
  -
    matrix:
      only:
        - job_name: Ubuntu
    init:
      - sh: sudo apt-get install -y libbrotli-dev
    test_script:
      - sh: scripts/ci_test.sh

  -
    matrix:
      only:
        - job_name: MacOS
    init:
      - sh: brew install brotli
    test_script:
      - sh: sudo -E scripts/ci_test.sh

  # -
  #  matrix:
  #    only:
  #      - job_name: Windows
  #  init:
  #    - cmd: set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  #  test_script:
  #    - cmd: C:\msys64\usr\bin\bash -cl "./scripts/ci_test.sh"
