language: ruby
rvm:
  - 2.6

os:
  - linux
  - osx

dist: bionic
osx_image: xcode11.2

arch:
  - amd64
  - arm64

addons:
  apt:
    packages:
      - libbrotli-dev
  homebrew:
    packages:
      - brotli

before_install:
  - gem install bundler

script:
  - scripts/ci_test.sh

env:
  global:
    - COVERALLS_PARALLEL=true

notifications:
  webhooks: https://coveralls.io/webhook
