language: ruby
rvm:
  - 2.6

os:
  - linux
  - osx

arch:
  - amd64
  - arm64

addons:
  apt:
    packages:
      - libbrotli-dev
    update: true
  homebrew:
    packages:
      - brotli
    update: true

before_install:
  - gem install bundler

script:
  - scripts/ci_test.sh
