language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7

dist: focal
osx_image: xcode11.6

jobs:
  include:
    - os: linux
      arch: amd64
    - os: osx
      arch: amd64

addons:
  apt:
    packages:
      - libbrotli-dev
  homebrew:
    packages:
      - brotli
    update: true

before_install:
  - gem install bundler

script:
  - scripts/ci_test.sh

after_success:
  - bash <(curl -s "https://codecov.io/bash")
