language: ruby
rvm:
  - 2.6

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libbrotli-dev
  homebrew:
    packages:
      - brotli

before_install:
  - gem install bundler

script:
  - scripts/ci_test.sh
