language: ruby

jobs:
  include:
    - os: linux
      arch: amd64
      dist: focal
      rvm: 2.5
    - os: linux
      arch: amd64
      dist: focal
      rvm: 2.6
    - os: linux
      arch: amd64
      dist: focal
      rvm: 2.7
    - os: osx
      arch: amd64
      osx_image: xcode12.2
      rvm: 2.5
    - os: osx
      arch: amd64
      osx_image: xcode12.2
      rvm: 2.6
    - os: osx
      arch: amd64
      osx_image: xcode12.2
      rvm: 2.7

addons:
  apt:
    packages:
      - libbrotli-dev
  homebrew:
    packages:
      - brotli

before_install:
  - gem install bundler

script:
  - scripts/ci_test.sh

after_success:
  - bash <(curl -s "https://codecov.io/bash")
