AlignAfterOpenBracket: AlwaysBreak
AlignConsecutiveMacros: true
AlignConsecutiveAssignments: true
AlignConsecutiveDeclarations: true
AlignEscapedNewlines: Left
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: true
BraceWrapping:
  AfterExternBlock: false
BreakBeforeBraces: Custom
BreakBeforeTernaryOperators: false
ColumnLimit: 120
Cpp11BracedListStyle: true
IndentExternBlock: false
IndentWrappedFunctionNames: true
KeepEmptyLinesAtTheStartOfBlocks: false
SpaceAfterCStyleCast: true
TabWidth: 2
