version: 2.1

jobs:
  build:
    docker:
      - image: puchuu/test-ruby-brs_x86_64-unknown-linux-gnu:latest
    working_directory: /mnt/data
    steps:
      - checkout
      - run: /home/ci_test.sh

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
